"""Schema definitions for storage backends."""

from __future__ import annotations

# Core tables and their schemas (SQL-neutral column definitions).
# Backends translate these to their own DDL.

TABLES: dict[str, list[tuple[str, str]]] = {
    "projects": [
        ("project_id", "TEXT PRIMARY KEY"),
        ("project_name", "TEXT NOT NULL"),
        ("cancer_type", "TEXT"),
        ("description", "TEXT"),
        ("pi_name", "TEXT"),
        ("institution", "TEXT"),
        ("irb_number", "TEXT"),
        ("created_at", "TIMESTAMP"),
        ("updated_at", "TIMESTAMP"),
        ("config_path", "TEXT"),
        ("data_dir", "TEXT"),
        ("output_dir", "TEXT"),
        ("patient_count", "INTEGER"),
    ],
    "patients": [
        ("patient_id", "TEXT PRIMARY KEY"),
        ("project_id", "TEXT NOT NULL"),
        ("mrn", "TEXT"),
        ("sex", "TEXT"),
        ("date_of_birth", "DATE"),
        ("age_at_dx", "INTEGER"),
        ("race", "TEXT"),
        ("ethnicity", "TEXT"),
        ("diagnosis_date", "DATE"),
        ("death_date", "DATE"),
        ("last_contact_date", "DATE"),
        ("kps", "INTEGER"),
        ("ecog", "INTEGER"),
        ("smoking_status", "TEXT"),
        ("pack_years", "REAL"),
    ],
    "encounters": [
        ("encounter_id", "TEXT PRIMARY KEY"),
        ("patient_id", "TEXT NOT NULL"),
        ("project_id", "TEXT NOT NULL"),
        ("encounter_type", "TEXT"),
        ("encounter_date", "DATE"),
        ("admit_datetime", "TIMESTAMP"),
        ("discharge_datetime", "TIMESTAMP"),
        ("department", "TEXT"),
        ("facility", "TEXT"),
        ("provider_name", "TEXT"),
        ("provider_specialty", "TEXT"),
        ("chief_complaint", "TEXT"),
    ],
    "conditions": [
        ("condition_id", "TEXT PRIMARY KEY"),
        ("patient_id", "TEXT NOT NULL"),
        ("project_id", "TEXT NOT NULL"),
        ("cancer_type", "TEXT"),
        ("icd10_code", "TEXT"),
        ("icd10_description", "TEXT"),
        ("histology", "TEXT"),
        ("histology_text", "TEXT"),
        ("primary_site", "TEXT"),
        ("laterality", "TEXT"),
        ("diagnosis_date", "DATE"),
        ("is_primary", "BOOLEAN"),
        ("is_recurrence", "BOOLEAN"),
    ],
    "tumor_assessments": [
        ("assessment_id", "TEXT PRIMARY KEY"),
        ("patient_id", "TEXT NOT NULL"),
        ("project_id", "TEXT NOT NULL"),
        ("condition_id", "TEXT"),
        ("assessment_date", "DATE"),
        ("clinical_t", "TEXT"),
        ("clinical_n", "TEXT"),
        ("clinical_m", "TEXT"),
        ("pathologic_t", "TEXT"),
        ("pathologic_n", "TEXT"),
        ("pathologic_m", "TEXT"),
        ("stage_group", "TEXT"),
        ("staging_system", "TEXT"),
        ("staging_edition", "TEXT"),
        ("grade", "TEXT"),
        ("tumor_size_cm", "REAL"),
        ("lymph_nodes_examined", "INTEGER"),
        ("lymph_nodes_positive", "INTEGER"),
        ("biomarkers", "TEXT"),  # JSON
    ],
    "medications": [
        ("medication_id", "TEXT PRIMARY KEY"),
        ("patient_id", "TEXT NOT NULL"),
        ("project_id", "TEXT NOT NULL"),
        ("condition_id", "TEXT"),
        ("encounter_id", "TEXT"),
        ("drug_name", "TEXT"),
        ("generic_name", "TEXT"),
        ("drug_class", "TEXT"),
        ("modality", "TEXT"),
        ("intent", "TEXT"),
        ("regimen_name", "TEXT"),
        ("cycle_number", "INTEGER"),
        ("start_date", "DATE"),
        ("end_date", "DATE"),
        ("dose", "TEXT"),
        ("dose_unit", "TEXT"),
        ("route", "TEXT"),
        ("frequency", "TEXT"),
        ("reason_stopped", "TEXT"),
    ],
    "procedures": [
        ("procedure_id", "TEXT PRIMARY KEY"),
        ("patient_id", "TEXT NOT NULL"),
        ("project_id", "TEXT NOT NULL"),
        ("condition_id", "TEXT"),
        ("encounter_id", "TEXT"),
        ("procedure_name", "TEXT"),
        ("procedure_code", "TEXT"),
        ("code_system", "TEXT"),
        ("modality", "TEXT"),
        ("intent", "TEXT"),
        ("procedure_date", "DATE"),
        ("surgeon", "TEXT"),
        ("findings", "TEXT"),
        ("margin_status", "TEXT"),
        ("total_dose_gy", "REAL"),
        ("fractions", "INTEGER"),
        ("technique", "TEXT"),
        ("treatment_site", "TEXT"),
    ],
    "lab_results": [
        ("lab_id", "TEXT PRIMARY KEY"),
        ("patient_id", "TEXT NOT NULL"),
        ("project_id", "TEXT NOT NULL"),
        ("encounter_id", "TEXT"),
        ("analyte_name", "TEXT"),
        ("analyte_code", "TEXT"),
        ("code_system", "TEXT"),
        ("value_numeric", "REAL"),
        ("value_text", "TEXT"),
        ("unit", "TEXT"),
        ("reference_low", "REAL"),
        ("reference_high", "REAL"),
        ("abnormal_flag", "TEXT"),
        ("collection_datetime", "TIMESTAMP"),
        ("result_datetime", "TIMESTAMP"),
    ],
    "imaging_reports": [
        ("imaging_id", "TEXT PRIMARY KEY"),
        ("patient_id", "TEXT NOT NULL"),
        ("project_id", "TEXT NOT NULL"),
        ("encounter_id", "TEXT"),
        ("study_date", "DATE"),
        ("modality", "TEXT"),
        ("body_region", "TEXT"),
        ("indication", "TEXT"),
        ("findings_text", "TEXT"),
        ("impression_text", "TEXT"),
        ("recist_category", "TEXT"),
        ("recist_timepoint", "TEXT"),
        ("sum_longest_diameters_mm", "REAL"),
        ("prior_sum_mm", "REAL"),
        ("percent_change", "REAL"),
        ("new_lesions", "BOOLEAN"),
        ("lesions", "TEXT"),  # JSON
    ],
    "progression_events": [
        ("progression_id", "TEXT PRIMARY KEY"),
        ("patient_id", "TEXT NOT NULL"),
        ("project_id", "TEXT NOT NULL"),
        ("condition_id", "TEXT"),
        ("event_date", "DATE"),
        ("progression_type", "TEXT"),
        ("site", "TEXT"),
        ("detection_method", "TEXT"),
        ("imaging_id", "TEXT"),
        ("notes", "TEXT"),
    ],
    "response_events": [
        ("response_id", "TEXT PRIMARY KEY"),
        ("patient_id", "TEXT NOT NULL"),
        ("project_id", "TEXT NOT NULL"),
        ("condition_id", "TEXT"),
        ("assessment_date", "DATE"),
        ("best_response", "TEXT"),
        ("assessment_method", "TEXT"),
        ("imaging_id", "TEXT"),
        ("treatment_line", "INTEGER"),
        ("notes", "TEXT"),
    ],
    "survival_events": [
        ("survival_id", "TEXT PRIMARY KEY"),
        ("patient_id", "TEXT NOT NULL"),
        ("project_id", "TEXT NOT NULL"),
        ("vital_status", "TEXT"),
        ("death_date", "DATE"),
        ("cause_of_death", "TEXT"),
        ("cancer_related_death", "BOOLEAN"),
        ("last_contact_date", "DATE"),
        ("last_known_alive_date", "DATE"),
    ],
    "derived_endpoints": [
        ("endpoint_id", "TEXT PRIMARY KEY"),
        ("patient_id", "TEXT NOT NULL"),
        ("project_id", "TEXT NOT NULL"),
        ("condition_id", "TEXT"),
        ("index_date", "DATE"),
        ("index_date_definition", "TEXT"),
        ("os_months", "REAL"),
        ("os_event", "BOOLEAN"),
        ("os_censor_date", "DATE"),
        ("os_censor_reason", "TEXT"),
        ("pfs_months", "REAL"),
        ("pfs_event", "BOOLEAN"),
        ("pfs_event_type", "TEXT"),
        ("pfs_event_date", "DATE"),
        ("pfs_censor_date", "DATE"),
        ("lc_months", "REAL"),
        ("lc_event", "BOOLEAN"),
        ("lc_event_date", "DATE"),
    ],
    "provenance": [
        ("id", "INTEGER PRIMARY KEY"),
        ("record_table", "TEXT NOT NULL"),
        ("record_id", "TEXT NOT NULL"),
        ("field_name", "TEXT NOT NULL"),
        ("field_value", "TEXT"),
        ("value_type", "TEXT"),
        ("source_adapter", "TEXT"),
        ("source_resource_type", "TEXT"),
        ("source_resource_id", "TEXT"),
        ("source_doc_id", "TEXT"),
        ("encounter_id", "TEXT"),
        ("doc_datetime", "TIMESTAMP"),
        ("page_no", "INTEGER"),
        ("char_start", "INTEGER"),
        ("char_end", "INTEGER"),
        ("bbox", "TEXT"),
        ("evidence_text", "TEXT"),
        ("normalized_text", "TEXT"),
        ("confidence", "REAL"),
        ("confidence_tier", "TEXT"),
        ("extraction_method", "TEXT"),
        ("review_status", "TEXT DEFAULT 'unreviewed'"),
        ("reviewer_id", "TEXT"),
        ("reviewed_at", "TIMESTAMP"),
    ],
}


def get_create_table_sql(table_name: str) -> str:
    """Generate CREATE TABLE IF NOT EXISTS SQL for a given table."""
    columns = TABLES[table_name]
    col_defs = ", ".join(f"{name} {typedef}" for name, typedef in columns)
    return f"CREATE TABLE IF NOT EXISTS {table_name} ({col_defs})"


def get_all_create_sql() -> list[str]:
    """Return CREATE TABLE statements for all tables."""
    return [get_create_table_sql(t) for t in TABLES]
